If the value is set during initialization but if the bounds set to be [None,None] then the value setter raises an `AttributeError: 'Variable' object has no attribute 'bounds'`